type: object
properties:
  id:
    $ref: '../common/uuid_id.yaml'
  description:
    type: string
    description: Product description
    minLength: 5
    maxLength: 255
  price:
    type: string
    format: '^[0-9]{1,3}(?:,?[0-9]{3})*\.[0-9]{2}$'
    description: Product price
  cost:
    type: string
#    format: '^[0-9]{1,3}(?:,?[0-9]{3})*\.[0-9]{2}$'
    format: '^-?(?:0|[1-9]\d{0,2}(?:,?\d{3})*)(?:\.\d+)?$'
    description: Product cost
  categories:
    type: array
    items:
      $ref: './Category.yaml'
  dimensions:
    $ref: './Dimensions.yaml'
  images:
    type: array
    items:
      $ref: './Image.yaml'
  created:
    $ref: '../common/iso_timestamp.yaml'
  modified:
    $ref: '../common/iso_timestamp.yaml'
required:
  - description
  - price