type: object
properties:
  id:
    $ref: '../common/uuid_id.yaml'
  uri:
    type: string
    format: url
    description: URI to the image
    minLength: 10
    maxLength: 511
    example: https://springframework.guru/wp-content/uploads/2019/08/spring-framework-guru-logo.jpg
  altText:
    type: string
    minLength: 3
    maxLength: 255
    nullable: true
required:
  -  uri
  -  id