type: object
description: The dimensions of the product (by default in cm)
properties:
  length:
    type: integer
    description: Product length
    minimum: 1
    maximum: 999
    nullable: true
  width:
    type: integer
    description: Product width
    minimum: 1
    maximum: 999
    nullable: true
  height:
    type: integer
    description: Product height
    minimum: 1
    maximum: 999
    nullable: true