name: Build docs
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Build docs
        shell: bash
        run: ./build.sh
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4 # https://github.com/peaceiris/actions-gh-pages
        with:
#          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          force_orphan: true
          exclude_assets: '.github,openapi,.redocly.yaml,LICENSE,README.md,build.sh'
#          cname: docs.api